import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import HeaderNavBar from "@/components/HeaderNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <Provider>
        <body className={inter.className}>
          <HeaderNavBar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
